package com.example.proyectofinaldisenomovil.domain.model.Event

//import com.google.firebase.Timestamp

import java.security.Timestamp

/**
 * Main entity: Community Event (Publicación).
 *
 * Firestore collection : "events"
 * Document ID          : auto-generated by Firestore
 *
 * Geographic queries use a "geohash" field (added by GeoFirestore) that is
 * NOT represented here but is written by [FirebaseEventRepository].
 */
data class Event(
    val id: String = "",
    val authorUid: String = "",
    /** Denormalized from User.fullName for fast feed rendering (no extra read). */
    val authorName: String = "",
    val title: String = "",
    val description: String = "",
    val category: EventCategory = EventCategory.SOCIAL,
    /** At least one image is required; URLs point to Cloudinary. */
    val imageUrls: List<String> = emptyList(),
    val latitude: Double = 0.0,
    val longitude: Double = 0.0,
    /** Human-readable address obtained via reverse geocoding. */
    val address: String = "",
    val startDate: Timestamp? = null,
    val endDate: Timestamp? = null,
    /** null means unlimited capacity. */
    val maxAttendees: Int? = null,
    /** Denormalized counter — updated atomically with FieldValue.increment. */
    val currentAttendees: Int = 0,
    val status: EventStatus = EventStatus.PENDING_REVIEW,
    /** UID of the moderator who verified or rejected this event. */
    val moderatorUid: String? = null,
    val rejectionReason: String? = null,
    /** Denormalized counter for "Es importante" votes. */
    val importantVotes: Int = 0,
    val isResolved: Boolean = false,
    /** Category suggested by the AI classifier (may differ from [category]). */
    val aiSuggestedCategory: String? = null,
    val createdAt: Timestamp? = null,
    val updatedAt: Timestamp? = null,
) {
    /** True when the event still accepts new attendees. */
    val hasCapacity: Boolean
        get() = maxAttendees == null || currentAttendees < maxAttendees

    /** True when the event is publicly visible in the feed. */
    val isPublic: Boolean
        get() = status == EventStatus.VERIFIED && !isResolved

    /** Thumbnail — first image URL or null when the list is empty. */
    val thumbnailUrl: String?
        get() = imageUrls.firstOrNull()
}
